# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

services:
  # frontend service for the React application
  app_frontend:
    build:
      context: ./react-facescanningapp
      dockerfile: Dockerfile
    container_name: app_frontend
    init: true
    volumes:
      - type: bind
        source: ./react-facescanningapp
        target: /app
      - type: volume
        target: /app/node_modules
    command: npm run dev
    ports:
      - "5173:5173"
    networks:
      - frontend

  # API service for face detection
  face_api:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
      target: dev
    init: true
    container_name: face_api
    command: uvicorn urls:api --host 0.0.0.0 --port 3001
    volumes:
      - type: bind
        source: ./fastapi
        target: /code
      - type: bind
        source: ./graphic
        target: /graphic
    depends_on:
      - db
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=YOUR-MONGODB-URI
      - SUPABASE_URL=SUPABASE-URL-CREDENTIAL
      - SUPABASE_KEY=SUPABASE-KEY-CREDENTIAL
    networks:
      - frontend
      - backend
    restart: unless-stopped

  # use mongo to store user data
  db:
    image: mongo:6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=facescanadmin
    volumes:
      - ./mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: always
    networks:
      - backend

volumes:
  mongo_data:

networks:
  frontend:
  backend:
